ngrok in cache

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -48,16 +48,28 @@ jobs:
           node-version: '23.x'
           cache: ${{ steps.detect-package-manager.outputs.manager }}
       
-      - name: Install ngrok
+      - name: Restore ngrok from cache
+        uses: actions/cache@v4
+        with:
+            path: /usr/local/bin/ngrok
+            key: ngrok-${{ runner.os }}-${{ hashFiles('**/.github/workflows/*.yml') }}
+            restore-keys: |
+              ngrok-${{ runner.os }}-
+  
+      - name: Install ngrok if not cached
         run: |
-          echo "$PWD"
-          curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
-          | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
-          && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
-          | sudo tee /etc/apt/sources.list.d/ngrok.list \
-          && sudo apt update \
-          && sudo apt install ngrok
-          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
+            if ! command -v ngrok &> /dev/null; then
+              echo "ngrok not found, installing..."
+              curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
+              | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
+              && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
+              | sudo tee /etc/apt/sources.list.d/ngrok.list \
+              && sudo apt update \
+              && sudo apt install ngrok
+            else
+              echo "ngrok is cached, skipping installation."
+            fi
+            ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
       
       - name: Expose Port 3000 with ngrok and start API server
         run: |
